### ISSUE TITLE
repositoryFormat isn't respecting date formats correctly

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom-proxy#27]
repositoryFormat=${year}-${month}-${day}/${feed}/${pathId}/${id}

is resulting in directories named

2018-11-18T20#20#03,123Z/MY_FEED/100/100

**Comment by GCHQ-11** [comment]
This seems to be a configuration issue. The date/time string above looks like the one that is prepended as part of being a 'rolling repository'.
If you omit the proxyRepositoryConfig -> rollCron setting, then the directories are named as perhaps expected.
