### ISSUE TITLE
Proxy zipFilenameTemplate should be allowed to accept directory content

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom-proxy#7]
To manage store_nodb proxy files, it would be useful to allow zipFilenameTemplate to contain directory elements. I would imagine the main change would be to move the id prefix value to the end of the template. For example the template (given a feed name of MY_FEED and remote address of 192.168.1.1)

>  ${feed}/${RemoteAddress}/

would result in the file

> MY_FEED/192.168.1.1/001.zip

Further one could allow keys such as ${year}, ${month}, ${day} to further augment the storage structure.

**Comment by stroomdev66** [comment]
This can now be done by setting the `repositoryFormat` parameter in the properties file.

**Comment by burnalting** [comment]
Is there, or can there be, documentation on keys available for the repositoryFormat parameter. For example, 
- are the list of keys in ./stroom-proxy/stroom-proxy-repo/src/main/java/stroom/proxy/repo/PathCreator.java:PathCreator:replaceTimeVars() one set of available keys?
- can keys be taken from a post's http header variables?

Happy to author/test this if one can point me to the relevant code.

**Comment by JustJellyfish** [comment]
So yes time vars as you've seen in the code, which are the same ones stroom supports for file output. These will relate to the time the file is written.

Any header argument that is passed. The key is case insensitive.

`${id}` will provide a sequential numeric id padded to multiples of 3 chars, e.g `001320`.

`${pathId}` will provide path elements as before that are related to the sequential id, e.g. for id `001320` you'd get `001/320`

Any non alpha numeric values (plus -._) are converted to underscores to ensure file name comparability.

Any part of a path that would exceed 256 characters is truncated.

The file name must start with `${id}` and then if you want anything else in the file name you must separate with an underscore.

Care must be taken to ensure paths won't exceed file system limitations, e.g. concatenating milliseconds plus seconds in a path could produce too many files or dirs in a single dir which might exceed the limit for the number of files in a directory on some file systems.

**Comment by stroomdev66** [comment]
So yes time vars as you've seen in the code, which are the same ones stroom supports for file output. These will relate to the time the file is written.

Any header argument that is passed. The key is case insensitive.

`${id}` will provide a sequential numeric id padded to multiples of 3 chars, e.g `001320`.

`${pathId}` will provide path elements as before that are related to the sequential id, e.g. for id `001320` you'd get `001/320`

The default pattern replicates the way proxy worked before and is therefore `${pathId}/${id}`

Any non alpha numeric values (plus -._) are converted to underscores to ensure file name compatability.

Any part of a path that would exceed 256 characters is truncated.

The file name must start with `${id}` and then if you want anything else in the file name you must separate with an underscore.

Care must be taken to ensure paths won't exceed file system limitations, e.g. concatenating milliseconds plus seconds in a path could produce too many files or dirs in a single dir which might exceed the limit for the number of files in a directory on some file systems.

**Comment by burnalting** [comment]
Thanks. I have deployed v5.1-beta.5 proxy and tested with a .28 beta app ... works great.
Using path `${feed}/${year}/${month}/${day}/${pathId}/${id}`

Will modify stroom-proxy howto on weekend to document new variable and also how to use it.
